name = "premier-stace-victory"
compatibility_date = "2024-07-25"

[pages]
build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "premier-stace-prod-db"
database_id = "e8997007-5f59-4cbd-abd1-140d9412a9cb"
